spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gdsc
    username: root
    password: dbwjddlRj
    driver-class-name: com.mysql.jdbc.Driver
#  jackson:
#    serialization:
#      fail-on-empty-beans: false #빈값은 직렬화하지 않음
server:
  port: 8081